package turbine.om;


import org.apache.torque.om.Persistent;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Sat Apr 13 23:23:40 IST 2019]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */
public  class TurbinePermission
    extends turbine.om.BaseTurbinePermission
    implements Persistent
{
    /** Serial version */
    private static final long serialVersionUID = 1555178020789L;

}
